name: fingerprint_auth_example
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^6.0.1
  local_auth: ^1.1.8
  http: ^0.13.3
  infinite_scroll_pagination: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true